import { makeStyles } from '@material-ui/core'

export const useStyle = makeStyles(theme => ({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    position: 'relative',
    '& > .header': {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      padding: '20px 15px',
      backgroundColor: theme.palette.secondary.main,
      opacity: 0.7,
      '& > span': {
        fontSize: 18,
      },
      '& > .filterIconContainer': {
        position: 'absolute',
        left: 10,
        bottom: 0,
        transform: 'translate(0, 50%)',
        backgroundColor: 'white',
        borderRadius: 10,
        cursor: 'pointer',
        '& > img': {
          maxHeight: 40,
        },
        '& > span': {
          backgroundColor: theme.palette.secondary.main,
          boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
          borderRadius: '50%',
          padding: '2px 8px',
          position: 'absolute',
          fontWeight: 'bold',
          top: -10,
          right: -10,
        },
      },
    },

    '& > .body': {
      display: 'flex',
      width: '100%',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '10px 10px 30px 10px',
      overflowY: 'auto',
      overflowX: 'hidden',
      '& > .event': {
        width: '100%',
        display: 'flex',
        borderRadius: 7,
        boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
        marginTop: 20,
        cursor: 'pointer',
        '& > img': {
          maxHeight: 50,
          minHeight: 50,
          minWidth: 110,
          maxWidth: 110,
          borderRadius: 7,
        },
        '& > div': {
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          paddingLeft: 15,
          fontSize: 18,
        },
      },
      '& > .selected': {
        border: `2px solid ${theme.palette.secondary.main}`,
      },
      '& > hr': {
        width: '90%',
        marginTop: 20,
      },
      '& > .musicFilterItem': {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        '& > span': {
          flex: 1,
          fontSize: 16,
        },
      },
      '& > .seeAllTextContainer': {
        width: '100%',
        display: 'flex',
        justifyContent: 'end',
        paddingRight: 10,
        paddingTop: 5,
        cursor: 'pointer',
      },
      '& > .switchItem': {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 7,
        '& > .left': {
          display: 'flex',
          alignItems: 'center',
          '& > img': {
            maxWidth: 25,
            maxHeight: 25,
          },
          '& > span': {
            fontSize: 18,
            paddingLeft: 10,
          },
        },
        '& > .right': {},
      },
      '& > .title': {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        paddingTop: 7,
        fontSize: 18,
        fontWeight: 'bold',
      },
      '& > .zonesContainer': {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        paddingTop: 25,
        overflowX: 'auto',
        paddingBottom: 25,
        '& > span': {
          textAlign: 'center',
          padding: 5,
          boxShadow: '2px 2px 2px 2px rgba(0, 0, 255, .1);',
          borderRadius: 7,
          minWidth: 100,
          maxWidth: 110,
          maxHeight: 40,
          cursor: 'pointer',
        },
        '& > .selected': {
          border: `2px solid ${theme.palette.secondary.main}`,
        },
        '& >*:not(:first-child)': {
          marginLeft: 10,
        },
      },
    },
  },
}))
