import { makeStyles } from '@material-ui/core'

export const useStyle = makeStyles(theme => ({
  '@keyframes focus': {
    from: {
      transform: 'scale(0.90)',
    },
    to: {
      transform: 'scale(1.05)',
    },
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    position: 'relative',
    overflowy: 'auto',
    '& > .header': {
      width: '100%',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '6px 15px',
      backgroundColor: '#fede11',
      opacity: 0.7,
      '& > .left': {
        display: 'flex',
        alignItems: 'center',
        '& > img': {
          height: 50,
          cursor: 'pointer',
        },
      },
      '& > .right': {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'end',
        flex: 1,
        height: 30,
        maxHeight: 30,
        '& > span': {
          display: 'flex',
          alignItems: 'center',
          height: '100%',
          width: '75%',
          backgroundColor: 'white',
          borderRadius: 10,
          marginRight: 10,
          paddingLeft: 10,
          cursor: 'pointer',
        },
        '& > img': {
          maxWidth: 30,
          maxHeight: 30,
          cursor: 'pointer',
        },
      },
      '& > .desktopRight': {
        display: 'flex',
        flex: 1,
        '& > .inputs': {
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          flex: 1,
          height: 35,
          '& > input': {
            height: '100%',
            width: '50%',
            border: 'none',
            borderRadius: 15,
            padding: '5px 10px',
            marginRight: 10,
            boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
            '&:focus': {
              outline: 'none',
            },
          },
          '& > span': {
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            height: '100%',
            padding: '5px 10px',
            backgroundColor: 'white',
            borderRadius: 15,
            boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
          },
          '& > .searchButtonContainer': {
            marginLeft: 10,
            height: '100%',
            width: 38,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            cursor: 'pointer',
            backgroundColor: 'white',
            borderRadius: '50%',
            boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
            '& > img': {
              maxWidth: 20,
              maxHeight: 20,
            },
          },
        },
        '& > img': {
          maxWidth: 30,
          maxHeight: 30,
          cursor: 'pointer',
        },
      },
    },
    '& > .body': {
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
      overflowX: ({ desktopMode }) => (!desktopMode ? 'auto' : ''),
      overflowY: ({ desktopMode }) => (!desktopMode ? 'auto' : ''),
      '& > .filterBar': {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: ({ desktopMode }) =>
          desktopMode ? '1px 1px 1px 1px rgba(0, 0, 255, .1);' : '',
        '& > .innerContainer': {
          display: 'flex',
          width: ({ desktopMode }) => (desktopMode ? 400 : '100%'),
          height: 40,
          maxHeight: 50,
          margin: 15,
          padding: '10px 15px',
          border: `2px solid ${theme.palette.secondary.main}`,
          borderRadius: 10,
          '& > div': {
            display: 'flex',
            alignItems: 'center',
            width: '33%',
            height: 20,
            cursor: 'pointer',
            borderRadius: 5,
            '& > .iconImage': {
              height: 22,
              maxHeight: 22,
              width: 22,
              maxWidth: 22,
            },
            '& > span': {
              marginLeft: 5,
            },
            '& > .downArrowImage': {
              maxHeight: 15,
              marginLeft: 5,
            },
          },
          '& > .date': {
            backgroundColor: ({ calendarModalOpen }) =>
              calendarModalOpen ? 'lightgrey' : '',
          },
          '& > .time': {
            flex: 1,
            paddingLeft: 10,
            borderRight: `1px solid lightGrey`,
            borderLeft: `1px solid lightGrey`,
            backgroundColor: ({ timeModalOpen }) =>
              timeModalOpen ? 'lightgrey' : '',
          },
          '& > .people': {
            paddingLeft: 10,
            backgroundColor: ({ peopleModalOpen }) =>
              peopleModalOpen ? 'lightgrey' : '',
          },
        },
      },
      '& > .eventTypesContainer': {
        display: 'flex',
        alignItems: 'center',
        height: 60,
        maxHeight: 60,
        marginTop: 20,
        paddingLeft: 15,
        width: '100%',
        '& > .filterIconContainer': {
          height: '100%',
          position: 'relative',
          '& > img': {
            maxHeight: 60,
            cursor: 'pointer',
          },
          '& > span': {
            backgroundColor: theme.palette.secondary.main,
            boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
            borderRadius: '50%',
            padding: '2px 8px',
            position: 'absolute',
            fontWeight: 'bold',
            top: -10,
            right: -10,
          },
        },
        '& > .itemsContainer': {
          height: '100%',
          display: 'flex',
          alignItems: 'center',
          overflowX: 'auto',
          padding: '0 15px',
          overflowY: 'auto',
          '& > div': {
            height: '100%',
            position: 'relative',
            marginLeft: 10,
            cursor: 'pointer',
            borderRadius: 10,
            '& > img': {
              maxWidth: 100,
              minWidth: 100,
              maxHeight: 60,
              borderRadius: 10,
              opacity: 0.7,
            },
            '& > span': {
              position: 'absolute',
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              color: 'white',
              fontWeight: 'bold',
            },
          },
          '& > .firstItem': {
            marginLeft: 0,
          },
          '& > .selected': {
            border: `1px solid ${theme.palette.secondary.main}`,
          },
        },
      },
      '& > .line': {
        width: '70%',
        content: null,
        borderBottom: '1px solid lightgrey',
        marginTop: 30,
      },
      '& > .filterTextContainer': {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 20,
        '& > span': {
          fontSize: 18,
        },
      },
      '& > .mainContainer': {
        display: 'flex',
        paddingBottom: 50,
        padding: 10,
        overflowY: ({ desktopMode }) => (desktopMode ? 'auto' : ''),
        '& > .foundItemsContainer': {
          overflowY: ({ desktopMode }) => (desktopMode ? 'auto' : ''),
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          flex: 1,
          overflowX: 'auto',
          paddingBottom: ({ desktopMode }) => (desktopMode ? 50 : 0),
          borderRight: ({ desktopMode }) =>
            desktopMode ? '1px solid lightgrey' : '',
          paddingRight: ({ desktopMode }) => (desktopMode ? 10 : 0),
          '& > .descContainer': {
            width: '100%',
            paddingLeft: 15,
            paddingTop: 10,
            '& > span': {
              fontSize: 16,
              fontWeight: 'bold',
            },
          },
          // overflowY: 'auto',
        },
        '& > .desktopFiltersContainer': {
          width: '43%',
          paddingLeft: 10,
          overflowY: 'auto',
        },
      },
    },
  },

  foundItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    padding: '20px 0 0 15px',
    '& > .left': {
      position: 'relative',
      height: '100%',
      cursor: 'pointer',
      '& > img': {
        maxHeight: 160,
        minHeight: 160,
        maxWidth: 170,
        minWidth: 170,
        borderRadius: 7,
      },
      '& > span': {
        position: 'absolute',
        borderRadius: '0 0 7px 7px',
        bottom: 5,
        left: 0,
        width: '100%',
        backgroundColor: 'white',
        opacity: 0.7,
        padding: '5px 10px',
        fontSize: 16,
      },
    },
    '& > .right': {
      height: 161,
      // maxWidth: 200,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      paddingLeft: 10,
      flex: 1,
      overflowX: 'auto',
      '& > .nameContainer': {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingRight: 10,
        '& > .name': {
          fontSize: 20,
          fontWeight: 'bold',
        },
        '& > .gift': {
          textAlign: 'center',
          backgroundColor: theme.palette.secondary.main,
          padding: '3px 12px',
          borderRadius: 7,
          fontWeight: 'bold',
          fontSize: 14,
        },
      },
      '& > .infoContainer': {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        flex: 1,
        '& > .address': {
          display: 'flex',
          alignItems: 'center',
          fontSize: 16,
          paddingRight: 35,
        },
        '& > .price': {
          display: 'flex',
          alignItems: 'center',
          fontSize: 16,
          paddingBottom: 5,
          '& > img': {
            maxHeight: 15,
          },
        },
        '& > .rate': {
          display: 'flex',
          alignItems: 'center',
          '& > img': {
            maxHeight: 17,
          },
          '& > span': {
            fontSize: 16,
            paddingLeft: 5,
          },
        },
      },
      '& > .eventList': {
        display: 'flex',
        alignItems: 'center',
        overflowX: 'auto',
        paddingRight: 5,
        height: 30,
        '& > span': {
          padding: '3px',
          borderRadius: 10,
          maxHeight: 30,
          // minWidth: 120,
          marginLeft: 5,
          boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
          whiteSpace: 'nowrap',
          display: 'flex',
          justifyContent: 'center',
        },
        '& > .firstItem': {
          marginLeft: 0,
        },

        '& > .selected': {
          border: `1px solid ${theme.palette.secondary.main}`,
        },
      },
    },
  },

  headerModalContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    zInex: 2001,
    '& img': {
      maxHeight: 20,
      cursor: 'pointer',
    },
    '& input': {
      border: 'none',
      flex: 1,
      padding: 3,
      height: '100%',
      '&:focus': {
        outline: 'none',
      },
    },
    '& > .left': {
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      width: '20%',
      maxWidth: 20,
    },
    '& > .right': {
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      flex: 1,
      maxWidth: 250,
      '& > .searchInputContainer': {
        display: 'flex',
        flexDirection: 'row-reverse',
        backgroundColor: 'white',
        alignItems: 'center',
        padding: 5,
        borderRadius: 10,
        height: 40,
      },
      '& > .locationInputContainer': {
        display: 'flex',
        backgroundColor: 'white',
        alignItems: 'center',
        padding: 5,
        marginTop: 10,
        borderRadius: 10,
      },
      '& > .local': {
        marginTop: 10,
      },
    },
  },
}))
