import { makeStyles } from '@material-ui/core'

export const useStyle = makeStyles(theme => ({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    position: 'relative',
    overflowY: 'auto',
    '& > .header': {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      // justifyContent: 'center',
      padding: '20px 10px',
      paddingLeft: 10,
      overflowX: 'auto',
      overflowY: 'hidden',
      '& > div': {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
        borderRadius: 15,
        padding: 5,
        paddingRight: 25,
        paddingLeft: 15,
        border: `1px solid ${theme.palette.secondary.main}`,
        marginLeft: 10,
        cursor: 'pointer',
        '& > img': {
          maxHeight: 15,
        },
        '& > span': {
          fontSize: 14,
          whiteSpace: 'nowrap',
          paddingLeft: 10,
        },
        '& > .countText': {
          backgroundColor: theme.palette.secondary.main,
          boxShadow: '1px 1px 1px 1px rgba(0, 0, 255, .1);',
          borderRadius: '50%',
          padding: '1px 6px',
          position: 'absolute',
          fontWeight: 'bold',
          top: -10,
          right: -10,
        },
        '& > .acceptIcon': {
          position: 'absolute',
          top: -10,
          right: -10,
          maxHeight: 20,
        },
      },
    },

    '& > .body': {
      display: 'flex',
      width: '100%',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '10px 10px 30px 10px',
      overflowY: 'auto',
      overflowX: 'hidden',
      '& > .card': {
        width: '100%',
        boxShadow: '2px 2px 2px 2px rgba(0, 0, 255, .1);',
        borderRadius: 15,
        padding: 10,
        marginTop: 15,
        '& > .titleContainer': {
          width: '100%',
          display: 'flex',
          '& > span': {
            fontSize: 22,
            fontWeight: 'bold',
            borderBottom: '1px solid grey',
          },
        },
        '& > .serataBody': {
          width: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          paddingTop: 10,
          '& > .event': {
            width: '100%',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 10,
            borderBottom: '1px solid lightgrey',
            paddingBottom: 10,
            '& > img': {
              maxHeight: 50,
              minHeight: 50,
              minWidth: 110,
              maxWidth: 110,
              borderRadius: 7,
            },
            '& > div': {
              height: '100%',
              display: 'flex',
              alignItems: 'center',
              '& > span': {
                fontSize: 18,
                whiteSpace: 'nowrap',
              },
            },
          },
        },
        '& > .localeBody': {
          display: 'flex',
          alignItems: 'center',
          overflowX: 'auto',
          overflowY: 'hidden',
          paddingTop: 20,
          '& > div': {
            height: '100%',
            position: 'relative',
            marginLeft: 10,
            cursor: 'pointer',
            borderRadius: 10,
            '& > img': {
              maxWidth: 100,
              minWidth: 100,
              maxHeight: 60,
              borderRadius: 10,
              opacity: 0.7,
            },
            '& > .selected': {
              border: `2px solid ${theme.palette.secondary.main}`,
            },
            '& > span': {
              position: 'absolute',
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              color: 'white',
              fontSize: 12,
              fontWeight: 'bold',
              textAlign: 'center',
            },
          },
          '& > .firstItem': {
            marginLeft: 0,
          },
          '& > .selected': {
            border: `1px solid ${theme.palette.secondary.main}`,
          },
        },
        '& > .zonesBody': {
          '& > div': {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderBottom: '1px solid lightgrey',
            '& > span': {
              fontSize: 14,
              whiteSpace: 'nowrap',
            },
          },
        },
      },
      '& > .selected': {
        border: `2px solid ${theme.palette.secondary.main}`,
      },
      '& > hr': {
        width: '90%',
        marginTop: 20,
      },
      '& > .musicFilterItem': {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        '& > span': {
          flex: 1,
          fontSize: 16,
        },
      },
      '& > .seeAllTextContainer': {
        width: '100%',
        display: 'flex',
        justifyContent: 'end',
        paddingRight: 10,
        paddingTop: 5,
        cursor: 'pointer',
      },
      '& > .switchItem': {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 7,
        '& > .left': {
          display: 'flex',
          alignItems: 'center',
          '& > img': {
            maxWidth: 25,
            maxHeight: 25,
          },
          '& > span': {
            fontSize: 18,
            paddingLeft: 10,
          },
        },
        '& > .right': {},
      },
      '& > .title': {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        paddingTop: 7,
        fontSize: 18,
        fontWeight: 'bold',
      },
      '& > .zonesContainer': {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        paddingTop: 25,
        overflowX: 'auto',
        paddingBottom: 25,
        '& > span': {
          textAlign: 'center',
          padding: 5,
          boxShadow: '2px 2px 2px 2px rgba(0, 0, 255, .1);',
          borderRadius: 7,
          minWidth: 100,
          maxWidth: 110,
          maxHeight: 40,
          cursor: 'pointer',
          // whiteSpace: 'nowrap',
        },
        '& > .selected': {
          border: `2px solid ${theme.palette.secondary.main}`,
        },
        '& >*:not(:first-child)': {
          marginLeft: 10,
        },
      },
    },
  },
}))
